### ISSUE TITLE
[Documentation] Typo in [.github/CONTRIBUTING.md]

### ISSUE THREAD

**Issue by alisajad001** [mojocss/mojocss#7] opened 2024-02-18 16:01 UTC
Hi there,
I hope you're doing well. While reviewing the "Contributing to Mojo CSS" documentation, I noticed a small typo that I'd like to bring to your attention.

Details:
Incorrect Word: [resquest]
Correction: [request]
Page/File: [.github/CONTRIBUTING.md]

**Comment by mimze** [comment] 2024-02-19 10:04
The issue is fixed now,
Thank you for your keen eye.

**Closed** 2024-02-19 10:04 UTC
